### PR TITLE
Expose entity.csv with flattened JSON fields [DO NOT MERGE UNTIL PERFORMANCE DISCUSSION]

### PR DESCRIPTION
**Pull request by Staberinde**
* Expose entity.csv with flattened JSON fields
* Run integration tests against a seperate, ephemeral database

`entity.csv` isn't particularly performant right now, the crux of the problem is twofold
1. Implementation is necessarily `O(n^2)` complex, as we have to parse the output once to get the fields to pass to `DictWriter` upon instantiation, then again to serialize the data. 
2. We are loading the data into memory rather than streaming.

I don't think 1) can be worked around unless we have some idea of what keys are present in `EntityOrm.json` in advance, but 2) could be. We would need to switch to an asynchronous psql driver for streaming to be practical however e.g. https://github.com/MagicStack/asyncpg

If we didn't have to support query filters, we could make use of preprocessing to aggregate the names of hoisted fields (over all datasets and/or per dataset), or even preprocess the entire response

### CODE REVIEW

**Comment by Staberinde** [comment]
So as I see it we have two use cases here:
1. I want to download a csv with hoisted fields with results matching filtering arguments (similar to `/entity.json` etc)
2. I want to download a csv with hoisted fields for an entire dataset

For use case 1), we use this new `/entity.csv` endpoint (but with pagination parameters enforced). 
For use case 2 we generate ane expose an additional csv file in S3 as part of the pipeline execution which contains each entity row for a dataset, but with the `json` fields hoisted

**Comment by ashimali** [comment]
I always thought use case 2 was the one that this whole discussions started with. (rememember is was CPRE asking for a csv download that prompted all this, not a request to package result of arbitrary entity search and filter as a csv)

In other words to replace the csv link on pages like this: https://www.digital-land.info/dataset/brownfield-land. That page links to [CSV](https://digital-land-production-collection-dataset.s3.eu-west-2.amazonaws.com/brownfield-land-collection/dataset/brownfield-land.csv). In other words the entire dataset albeit with json blob shoved into the csv file. 

It could be done as part of pipeline execution to build another static csv file with json flattened or as a task that runs separately (in the same was as the load of db into info app is) and dumps to bucket that is solely used by info app. Which is what I meant on ticket when referring to pre processing. I'm not that concerned about where the work is done, however I'm not sure why we're implementing use case 1 at this point for this card.

**Comment by Staberinde** [comment]
Not sure, I implemented it because Paul indicated on the card that he wanted use case 1 supported as well

**Comment by Staberinde** [comment]
> 1. we pack fields which aren't common to every entity in the json database column, but I think these should be flattened / hoisted in the API. I can see this might be OK for an "object" format of JSON, but it's what users will expect when we're returning GeoJSON or CSV (or ttl, etc).

That's fine, we can accomplish that, either by serving a static hoisted CSV or finding some way of getting streaming a whole dataset to be practical 

> 2. The link on the /dataset/{dataset}.{format} should return the whole dataset without pagination. I think this can be a separate path to /entity? which can always be paginated. This isn't just for CSV, I'd expect to be able to get a dump of the whole dataset as JSON, turtle, etc.

Similar to above, for the case of CSV we have a solution to this. If it's necessary to make changes to serve files per dataset for other formats (JSON, turtle etc) and link to them from `/datasets`, then we can make another ticket to implement that.

> 3. If the app can stream the dataset, or if we have to bake each dataset as a static download on s3

In the case of CSV, where the hoisted fields have to be known before the file can be streamed (to populate the headers), i'm skeptical that streaming is practical for an entire dataset. But a similar asynchronous approach described in your datasettee link could be used for other file formats (certainly JSON, not sure about turtle, xls etc)

The limitation right now is that SQLAlchemy is being used in a thread-local manner, so any asynchronous (`yield`/`yield from`) processing runs into the issue of [unbound model instances](https://docs.sqlalchemy.org/en/14/errors.html#error-bhk3) due to the `session` being thread local. So we need to (at least) allow SQLAlchemy to work in an asynchronous way, which may not be a trivial piece of work (A toy example of what this might look like can be found [here](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html)).

This is similar to what datasettee is describing. It's worth noting that they truncate streamed CSV's at 100MB, and some of our dataset CSV's are larger than that (e.g. listed buildings at 244MB) so that suggests that they've run into limitations in streaming, even handling the process fully asynchronously, and without the overhead associated with field hoisting. 

To get an idea of what performance looks like now, it takes 106 seconds to serve the unpaginated response to `entity.csv?dataset=listed-building`:

```
| Method: GET, Path: /entity.csv, Duration: 106.6760826180107, Status: 200
web_1  |
web_1  |   _     ._   __/__   _ _  _  _ _/_   Recorded: 09:52:58  Samples:  5208
web_1  |  /_//_/// /_\ / //_// / //_'/ //     Duration: 266.690   CPU time: 253.637
web_1  | /   _/                      v4.1.1
web_1  |
web_1  | Program: /usr/local/bin/gunicorn -k uvicorn.workers.UvicornWorker -c /src/gunicorn_conf.py application.app:app
web_1  |
web_1  | 266.689 run  asyncio/runners.py:8
web_1  | `- 266.686 coro  starlette/middleware/base.py:28
web_1  |    `- 266.686 __call__  fastapi_profiler/profiler_middleware/profiler.py:35
web_1  |       |- 160.009 __call__  starlette/middleware/cors.py:74
web_1  |       |  `- 160.009 __call__  starlette/exceptions.py:56
web_1  |       |     `- 160.009 __call__  starlette/routing.py:635
web_1  |       |        `- 160.009 handle  starlette/routing.py:251
web_1  |       |           `- 160.009 app  starlette/routing.py:58
web_1  |       |              `- 160.005 app  fastapi/routing.py:186
web_1  |       |                 `- 159.911 run_endpoint_function  fastapi/routing.py:151
web_1  |       |                    `- 159.911 run_in_threadpool  starlette/concurrency.py:27
web_1  |       |                       `- 159.911 run_sync  anyio/to_thread.py:10
web_1  |       |                          `- 159.911 run_sync_in_worker_thread  anyio/_backends/_asyncio.py:778
web_1  |       |                             `- 3.043 [await]
web_1  |       `- 106.673 __call__  starlette/middleware/cors.py:74
web_1  |          `- 106.672 __call__  starlette/exceptions.py:56
web_1  |             `- 106.671 __call__  starlette/routing.py:635
web_1  |                `- 106.668 handle  starlette/routing.py:251
web_1  |                   `- 106.667 app  starlette/routing.py:58
web_1  |                      `- 106.667 app  fastapi/routing.py:186
web_1  |                         `- 106.562 run_endpoint_function  fastapi/routing.py:151
web_1  |                            `- 106.562 run_in_threadpool  starlette/concurrency.py:27
web_1  |                               `- 106.562 run_sync  anyio/to_thread.py:10
web_1  |                                  `- 106.562 run_sync_in_worker_thread  anyio/_backends/_asyncio.py:778
web_1  |                                     `- 3.193 [await]
web_1  |
web_1  |
web_1  | 172.20.0.1:57428 - "GET /entity.csv?dataset=listed-building HTTP/1.1" 200
```

**Comment by Staberinde** [comment]
Closing now due to performance issues, some unrelated dev environment improvements from this branch are now in separate PR https://github.com/digital-land/digital-land.info/pull/32

**Pull request closed without merging**
