### PR TITLE
Update maps

### PR DESCRIPTION
**Pull request by GeorgeGoodall**
ticket: https://trello.com/c/hXFatrUP/188-make-maps-uniform-on-dlinfo

### Changes made: 
 - Made a new map component to be used across the whole site that enables better configuration of the map and easier reuse
 - Added JavaScript unit/integration tests for the map code (using vitest)
 - Made some visual/functional changes to the map:
   - New zoom control with removed arbitrary zoom level
   - use of pin in map layer selector to more clearly indicate a point
   - New button to allow tilting of map from 2D to 3D
   - New Scale indicator at the bottom of the map

image
image

### Further tickets to make
- Acceptance/e2e tests should be written in python playwright
- We should look into making the map more accessible

### CODE REVIEW

**Comment by GeorgeGoodall** [comment]
For the map on the entity page and search page, we should have a map control that is "return to feature". so you can easily find the feature again if you pan away from it

@mdsmith-scottlogic do you think I should do this as part of this PR or another ticket?

**Comment by GeorgeGoodall** [comment]
getting
Error: Cannot style non-existing layer "local-authority-district-source-fill".

it doesn't seem to impact the execution of the map. but we should investigate why this is happening.

image

**Comment by GeorgeGoodall** [comment]
using the mouse wheel on a popup is scrolling the page instead of zooming in/out

image

(this existed prior to these changes. but perhaps we should fix this as part of this PR or make a new ticket)

**Comment by mdsmith-scottlogic** [comment]
> For the map on the entity page and search page, we should have a map control that is "return to feature". so you can easily find the feature again if you pan away from it
> 
> @mdsmith-scottlogic do you think I should do this as part of this PR or another ticket?

Do it as another ticket please!

**Comment by mdsmith-scottlogic** [comment]
> using the mouse wheel on a popup is scrolling the page instead of zooming in/out
> 
> image
> 
> (this existed prior to these changes. but perhaps we should fix this as part of this PR or make a new ticket)

New ticket!

**Comment by GeorgeGoodall** [comment]
Samantha spotted the content under the map has gone missing will add back in shortly

**Review by mdsmith-scottlogic — APPROVED** [review]

**Review by mdsmith-scottlogic — APPROVED** [review]

**Review by mdsmith-scottlogic — APPROVED** [review]
Approved. Please lets get this in before we go over 100 commits :-)

**Pull request merged**
